---
# region General configuration
SHOW_ELAPSED_TIME: false
IGNORE_GITIGNORED_FILES: true
CLEAR_REPORT_FOLDER: true
IGNORE_GENERATED_FILES: true # We do not want to lint generated files

EXCLUDED_DIRECTORIES:
  # Generated reports/documentation
  - megalinter-reports
  - docs
  - .idea
  - .vscode
# endregion

# region Reporters configuration
SARIF_REPORTER: true # SARIF allows for better integration with IDEs and other tools
SARIF_REPORTER_NORMALIZE_LINTERS_OUTPUT: true # Normalize SARIF output to make it more readable
JSON_REPORTER: true # JSON is useful for manual inspection
TEXT_REPORTER: true # Linter logs are nice to have an overview
CONSOLE_REPORTER: true # It is userfull to have a console output from the run
UPDATED_SOURCES_REPORTER: false # Building a repository patch
GITHUB_COMMENT_REPORTER: false # Commenting on PR introduces unnecessary cluter
GITHUB_STATUS_REPORTER: true # Status is useful to have a quick feedback in PR (can be merged, code annotations)
# endregion

# region Disabling linters
FORMATTERS_DISABLE_ERRORS: false # We want to enforce formating rules as well

DISABLE:
  - SPELL # spellchecking is truely error prone

DISABLE_LINTERS:
  - SQL_TSQLLINT # .NET Core is not installed - always fails
  - JSON_V8R # Most schemas are not supported
  - YAML_V8R # Most schemas are not supported
  - PYTHON_ISORT # We can live without alphabetically sorted imports - something to consider in future
  - PYTHON_PYRIGHT # I cannot get imports to work with this linter
  - HTML_HTMLHINT # It does not align with frameworks like Angular
  - MARKDOWN_MARKDOWN_LINK_CHECK # It is prone to false positives for internal links
  - REPOSITORY_KICS # It is too strict and does not align with our current security policies
  - REPOSITORY_SECRETLINT # Crashes while trying to read /tmp/lint/megalinter-reports/copy-paste/html/index.html ?!

# Disable errors but keep them as warnings
DISABLE_ERRORS_LINTERS:
  - REPOSITORY_TRIVY # We are locked with old dependencies, leaving as a warning to be addressed in the future
  - OPENAPI_SPECTRAL # Simply cannot get it right
  - MARKDOWN_MARKDOWNLINT # Not high priority but need to be manually curated for generated files - high effort
  - REPOSITORY_CHECKOV # Have problem with understanding the issues

# endregion

# region Linters configuration
# region Defaults adopted from megalinter own configuration
SPELL_VALE_FILE_EXTENSIONS:
  - .md
DOCKERFILE_HADOLINT_ARGUMENTS: "--ignore DL3003 --ignore DL3007 --ignore DL3013 --ignore DL3016 --ignore DL3018 --ignore DL3028 --ignore DL3059 --ignore DL4001 --ignore DL4006 --ignore SC2015 --ignore SC2016 --ignore SC2039 --ignore SC2086 --ignore SC1091 --ignore SC3046"
# endregion

PYTHON_PYLINT_ARGUMENTS: "--disable=import-error" # By default, when running these imports are not resolved

COPYPASTE_JSCPD_ARGUMENTS: "--min-tokens 300" # Raise the minimum number of tokens to consider a duplication - trying to reduce changes

REPOSITORY_CHECKOV_ARGUMENTS: "--skip-check CKV_GHA_7" # allow action workflow dispatch inputs https://docs.prismacloud.io/en/enterprise-edition/policy-reference/build-integrity-policies/github-actions-policies/github-actions-contain-workflow-dispatch-input-parameters

REPOSITORY_KICS_ARGUMENTS: "--disable-secrets" # We do not want to scan for secrets, this is done by other linters
# endregion
