APPLY_FIXES: none

SHOW_ELAPSED_TIME: false

SARIF_REPORTER: true
SARIF_REPORTER_NORMALIZE_LINTERS_OUTPUT: false
JSON_REPORTER: true
TEXT_REPORTER: true
CONSOLE_REPORTER: true
UPDATED_SOURCES_REPORTER: false
GITHUB_COMMENT_REPORTER: false
GITHUB_STATUS_REPORTER: true

DISABLE:
#  - CLOUDFORMATION
#  - COPYPASTE
#  - CSS
#  - EDITORCONFIG
  - SPELL
#  - JAVASCRIPT
#  - TEKTON
DISABLE_LINTERS:
  - SQL_TSQLLINT # .NET Core is not installed - always fails
  - JSON_V8R # Most schemas are not supported
  - YAML_V8R # Most schemas are not supported
  - PYTHON_ISORT # We can live without alphabetically sorted imports - something to consider in future
  - PYTHON_PYRIGHT # I cannot get imports to work with this linter
  - HTML_HTMLHINT # It does not align with frameworks like Angular

 # Disable errors but keep them as warnings
DISABLE_ERRORS_LINTERS:
#  - BASH_EXEC
  - BASH_SHELLCHECK
  - BASH_SHFMT
  - C_CPPLINT
  - C_CLANG_FORMAT
  - CLOJURE_CLJ_KONDO
  - CLOJURE_CLJSTYLE
  - COFFEE_COFFEELINT
  - CPP_CPPLINT
  - CPP_CLANG_FORMAT
  - CSHARP_DOTNET_FORMAT
  - CSHARP_CSHARPIER
#  - CSHARP_ROSLYNATOR
  - DART_DARTANALYZER
  - GO_GOLANGCI_LINT
  - GO_REVIVE
#  - GROOVY_NPM_GROOVY_LINT
  - JAVA_CHECKSTYLE
  - JAVA_PMD
  - JAVASCRIPT_ES
  - JAVASCRIPT_STANDARD
#  - JAVASCRIPT_PRETTIER
  - JSX_ESLINT
  - KOTLIN_KTLINT
  - KOTLIN_DETEKT
  - LUA_LUACHECK
  - MAKEFILE_CHECKMAKE
  - PERL_PERLCRITIC
  - PHP_PHPCS
  - PHP_PHPSTAN
  - PHP_PSALM
  - PHP_PHPLINT
  - POWERSHELL_POWERSHELL
#  - POWERSHELL_POWERSHELL_FORMATTER
  - PYTHON_PYLINT
  - PYTHON_BLACK
  - PYTHON_FLAKE8
  - PYTHON_ISORT
  - PYTHON_BANDIT
  - PYTHON_MYPY # just warn on incorrect types
  - PYTHON_PYRIGHT
#  - PYTHON_RUFF
  - R_LINTR
  - RAKU_RAKU
  - RUBY_RUBOCOP
  - RUST_CLIPPY
  - SALESFORCE_SFDX_SCANNER_APEX
  - SALESFORCE_SFDX_SCANNER_AURA
  - SALESFORCE_SFDX_SCANNER_LWC
  - SALESFORCE_LIGHTNING_FLOW_SCANNER
  - SCALA_SCALAFIX
  - SQL_SQL_LINT
  - SQL_SQLFLUFF
  - SQL_TSQLLINT
  - SWIFT_SWIFTLINT
  - TSX_ESLINT
  - TYPESCRIPT_ES
  - TYPESCRIPT_STANDARD
#  - TYPESCRIPT_PRETTIER
  - VBDOTNET_DOTNET_FORMAT
  ## Formats
  - CSS_STYLELINT
  - CSS_SCSS_LINT
  - ENV_DOTENV_LINTER
  - GRAPHQL_GRAPHQL_SCHEMA_LINTER
  - HTML_DJLINT
  - HTML_HTMLHINT
  - JSON_JSONLINT
  - JSON_ESLINT_PLUGIN_JSONC
  - JSON_V8R
#  - JSON_PRETTIER
  - JSON_NPM_PACKAGE_JSON_LINT
  - LATEX_CHKTEX
  - MARKDOWN_MARKDOWNLINT
  - MARKDOWN_REMARK_LINT
  - MARKDOWN_MARKDOWN_LINK_CHECK
  - MARKDOWN_MARKDOWN_TABLE_FORMATTER
  - PROTOBUF_PROTOLINT
  - RST_RST_LINT
  - RST_RSTCHECK
  - RST_RSTFMT
#  - XML_XMLLINT
#  - YAML_PRETTIER
  - YAML_YAMLLINT
  - YAML_V8R
  ## Tooling formats
  - ACTION_ACTIONLINT
  - ANSIBLE_ANSIBLE_LINT
  - ARM_ARM_TTK
  - BICEP_BICEP_LINTER
  - CLOUDFORMATION_CFN_LINT
  - DOCKERFILE_HADOLINT
  - EDITORCONFIG_EDITORCONFIG_CHECKER
  - GHERKIN_GHERKIN_LINT
  - KUBERNETES_KUBECONFORM
  - KUBERNETES_HELM
  - KUBERNETES_KUBESCAPE
  - OPENAPI_SPECTRAL
  - PUPPET_PUPPET_LINT
  - SNAKEMAKE_LINT
  - SNAKEMAKE_SNAKEFMT
  - TEKTON_TEKTON_LINT
  - TERRAFORM_TFLINT
  - TERRAFORM_TERRASCAN
  - TERRAFORM_TERRAGRUNT
  - TERRAFORM_TERRAFORM_FMT
  ## Other
  - COPYPASTE_JSCPD
  - REPOSITORY_CHECKOV
  - REPOSITORY_DEVSKIM
#  - REPOSITORY_DUSTILOCK
#  - REPOSITORY_GIT_DIFF
  - REPOSITORY_GITLEAKS
  - REPOSITORY_GRYPE
  - REPOSITORY_KICS
  - REPOSITORY_SECRETLINT
  - REPOSITORY_SEMGREP
#  - REPOSITORY_SYFT
  - REPOSITORY_TRIVY
#  - REPOSITORY_TRIVY_SBOM
#  - REPOSITORY_TRUFFLEHOG
  - SPELL_CSPELL
  - SPELL_PROSELINT
  - SPELL_VALE
  - SPELL_LYCHEE

SPELL_VALE_FILE_EXTENSIONS:
  - .md
DOCKERFILE_HADOLINT_ARGUMENTS: "--ignore DL3003 --ignore DL3007 --ignore DL3013 --ignore DL3016 --ignore DL3018 --ignore DL3028 --ignore DL3059 --ignore DL4001 --ignore DL4006 --ignore SC2015 --ignore SC2016 --ignore SC2039 --ignore SC2086 --ignore SC1091 --ignore SC3046"

PYTHON_PYLINT_ARGUMENTS: "--disable=import-error"

COPYPASTE_JSCPD_ARGUMENTS: "--min-tokens 300"
